Repository nextcloud/registration, pull requests merged in 2020-11, with the labels that each got.

#255 Don't allow limiting to groups
  appinfo/info.xml
Labels: 3. to review, backport-request, technical debt

#248 Make mail confirmation optional
  lib/Controller/RegisterController.php
  lib/Controller/SettingsController.php
  lib/Service/RegistrationService.php
  lib/Settings/RegistrationSettings.php
  templates/admin.php
  templates/form/email.php
  tests/Unit/Controller/RegisterControllerTest.php
Labels: 3. to review, bug, feature: settings ⚙️

#258 Forward error messages of the password policy directly
  templates/form/user.php
Labels: 3. to review, bug, feature: frontend 🖌️
