Repository nextcloud/registration, pull requests merged in 2020-07, with the labels that each got.

#214 Check coding standard
  .github/workflows/lint.yml
  .gitignore
  .php_cs.cache
  .php_cs.dist
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/ApiController.php
  lib/Controller/RegisterController.php
  lib/Controller/SettingsController.php
  lib/Db/Registration.php
  lib/Db/RegistrationMapper.php
  lib/Service/MailService.php
  lib/Service/RegistrationException.php
  lib/Service/RegistrationService.php
  lib/Settings/RegistrationSettings.php
  lib/Util/CoreBridge.php
  templates/admin.php
  templates/domains.php
  templates/email.newuser.disabled_html.php
  templates/email.newuser.disabled_plaintext.php
  templates/email.newuser_html.php
  templates/email.newuser_plaintext.php
  templates/email.validate_html.php
  templates/email.validate_plaintext.php
  templates/form.php
  templates/message.php
  templates/register.php
  tests/Integration/Controller/RegisterControllerTest.php
  tests/Integration/Service/RegistrationServiceTest.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: 3. to review, technical debt

#217 Update testing matrix and nextcloud requirements
  .travis.yml
  appinfo/info.xml
Labels: 3. to review, technical debt

#218 Execute the tests correctly again
  tests/Integration/Controller/RegisterControllerTest.php
  tests/Integration/Service/RegistrationServiceTest.php
  tests/Unit/Controller/ApiControllerTest.php
  tests/phpunit.integration.xml
  tests/phpunit.xml
  tests/scripts/phpunit.sh
Labels: 3. to review, bug

#222 Objects are always passed by reference
  lib/Db/RegistrationMapper.php
  lib/Service/RegistrationService.php
  tests/Integration/Controller/RegisterControllerTest.php
  tests/Integration/Service/RegistrationServiceTest.php
Labels: 3. to review, technical debt

#224 Validate the info.xml with a github workflow
  .github/workflows/lint.yml
  .travis.yml
  tests/scripts/lint-appinfo.sh
  tests/scripts/lint-php.sh
Labels: 3. to review, technical debt

#223 Move to migration
  .travis.yml
  appinfo/database.xml
  appinfo/info.xml
  lib/Migration/Version0005Date20200710135953.php
  tests/scripts/core-download.sh
  tests/scripts/core-setup.sh
Labels: 3. to review, technical debt

#225 Updated Supported Software
  README.md
Labels: 3. to review

#227 Update .gitignore
  .gitignore
  .php_cs.cache
Labels: 3. to review, technical debt

#228 Use non-deprecated QBMapper
  lib/Db/Registration.php
  lib/Db/RegistrationMapper.php
Labels: 3. to review, technical debt

#226 Remove unnecessary compatibility layers
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Controller/SettingsController.php
  lib/Db/RegistrationMapper.php
  lib/Settings/RegistrationSettings.php
  lib/Util/CoreBridge.php
  templates/form.php
  templates/message.php
  templates/register.php
  tests/Unit/Controller/ApiControllerTest.php
Labels: 3. to review, technical debt

#219 Use the primary color and adjust the width when it's the only option
  appinfo/app.php
  css/register-button.css
Labels: 3. to review, bug, feature: frontend 🖌️

#221 Fix checkbox style in admin settings
  templates/admin.php
Labels: 3. to review, bug, feature: frontend 🖌️, feature: settings ⚙️

#229 Update info.xml to new location
  README.md
  appinfo/info.xml
  appinfo/screenshot.png
Labels: 3. to review, bug

#231 Fix show password option
  js/form.js
  templates/form.php
Labels: 3. to review, bug, feature: frontend 🖌️

#232 Add a "Back to login" link similar to the forgot password page
  templates/admin.php
  templates/domains.php
  templates/form.php
  templates/message.php
  templates/register.php
Labels: 3. to review, bug, feature: frontend 🖌️

#220 Move emails to IEmailTemplate
  lib/Service/MailService.php
  templates/email.newuser.disabled_html.php
  templates/email.newuser.disabled_plaintext.php
  templates/email.newuser_html.php
  templates/email.newuser_plaintext.php
  templates/email.validate_html.php
  templates/email.validate_plaintext.php
  tests/Integration/Controller/RegisterControllerTest.php
Labels: 3. to review, enhancement

#230 Register login option via public API
  .travis.yml
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/RegistrationLoginOption.php
Labels: 3. to review, technical debt
