Repository nextcloud/registration, pull requests merged in 2021-11, with the labels that each got.

#352 Fix language of hint exceptions
  .github/workflows/phpunit.yml
  lib/Controller/RegisterController.php
Labels: 3. to review, bug, feature: api 🛠️

#358 Update npm and node engines versions
  package.json
Labels: dependencies

#364 Add option to make email optional
  .github/workflows/phpunit.yml
  appinfo/info.xml
  css/style.css
  js/registration-settings.js
  js/registration-settings.js.map
  lib/Controller/RegisterController.php
  lib/Controller/SettingsController.php
  lib/Service/RegistrationService.php
  lib/Settings/RegistrationSettings.php
  src/AdminSettings.vue
  templates/form/email.php
  templates/form/user.php
  tests/Unit/Controller/RegisterControllerTest.php
Labels: 3. to review, enhancement, feature: settings ⚙️
