Repository nextcloud/registration, pull requests merged in 2021-04, with the labels that each got.

#280 Feature/noid/more profile fields
  .eslintignore
  .eslintrc.js
  .gitattributes
  .github/workflows/app-code-check.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .gitignore
  .l10nignore
  Makefile
  babel.config.js
  css/style.css
  js/registration-settings.js
  js/registration-settings.js.map
  js/settings.js
  lib/Controller/RegisterController.php
  lib/Controller/SettingsController.php
  lib/Service/MailService.php
  lib/Service/RegistrationService.php
  lib/Settings/RegistrationSettings.php
  package-lock.json
  package.json
  src/AdminSettings.vue
  src/settings.js
  stylelint.config.js
  templates/admin.php
  templates/form/email.php
  templates/form/user.php
  tests/Unit/Controller/RegisterControllerTest.php
  tests/Unit/Service/RegistrationServiceTest.php
  webpack.js
Labels: 3. to review, enhancement, feature: frontend 🖌️, feature: settings ⚙️

#281 Move from ILogger to LoggerInterface
  lib/Service/MailService.php
  lib/Service/RegistrationService.php
  tests/Unit/Service/RegistrationServiceTest.php
Labels: technical debt

#284 Fix registration with loginname field
  templates/form/user.php
Labels: 3. to review, bug, regression

#286 Improve registration submission form
  .eslintrc.js
  .gitattributes
  .l10nignore
  js/form.js
  js/registration-form.js
  js/registration-form.js.map
  js/registration-settings.js
  js/registration-settings.js.map
  lib/Controller/RegisterController.php
  package-lock.json
  package.json
  src/form.js
  templates/form/email.php
  templates/form/user.php
  templates/form/verification.php
  tests/Unit/Controller/RegisterControllerTest.php
  webpack.js
Labels: 3. to review, bug, feature: frontend 🖌️

#294 l10n: Unify spelling
  js/registration-settings.js
  js/registration-settings.js.map
  src/AdminSettings.vue
Labels: 4. to release

#293 Terms of service integration
  lib/Controller/RegisterController.php
  lib/Events/AFormEvent.php
  lib/Events/PassedFormEvent.php
  lib/Events/ShowFormEvent.php
  lib/Events/ValidateFormEvent.php
  templates/form/email.php
  tests/Unit/Controller/RegisterControllerTest.php
Labels: 3. to review, enhancement

#295 Add changelog for 1.2.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#299 Prevent the hash appearing when showing the password
  js/registration-form.js
  js/registration-form.js.map
  src/form.js
Labels: 3. to review, bug, feature: frontend 🖌️

#300 Fix registration with Talk iOS app
  lib/Controller/RegisterController.php
Labels: 3. to review, bug, feature: api 🛠️
