Repository nextcloud/registration, pull requests merged in 2022-08, with the labels that each got.

#441 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#443 Update npm and node engines versions
  package.json
Labels: dependencies

#444 Fix minor things
  lib/Controller/RegisterController.php
  package-lock.json
  templates/approval-required.php
  templates/form/email.php
  tests/Unit/Controller/RegisterControllerTest.php
Labels: 3. to review, bug, feature: frontend 🖌️

#453 Allow spaces in allowed_domains config
  lib/Controller/RegisterController.php
  lib/Service/RegistrationService.php
  tests/Unit/Controller/RegisterControllerTest.php
  tests/Unit/Service/RegistrationServiceTest.php
Labels: 3. to review, bug, feature: api 🛠️
